export const CORE_PLAYERS: string[] = [
  "Zouzou",
  "Nick",
  "Howie",
  "Cat Stevens",
  "Pita Poulet",
  "Bastille",
  "Prison Mike",
  "Galatea",
  "Blackie",
  "Du Maurier",
  "Nora",
  "Rolo",
  // "Test13",
  // "Test14",
  // "Test15",
  // "Test16",
  // "Test17",
  // "Test18",
  // "Test19",
  // "Test20",
];
